### ISSUE TITLE
not accepted

### ISSUE THREAD

**Issue by 02Benedicte** [jpenriquez90/Zoom-Practice-Test#3]
the request has not been validated .Can you please review

**Comment by jpenriquez90** [comment]
the issue has been fixed.

**Comment by jpenriquez90** [comment]
It is still not working.

**Comment by 02Benedicte** [comment]
i want to see you trying

**Comment by jpenriquez90** [comment]
this issue will be closed.

**Comment by 02Benedicte** [comment]
@jpenriquez90 
I am not satisfied can you please review the issue?

**Comment by solangengum** [comment]
@jpenriquez90 
can you reopen issue?

**Comment by jpenriquez90** [comment]
closing the issue now - Josh
